$color = rgba(0, 0, 2, 1)
$inner_color = rgba(0, 0, 2, 0.66)
$outer_color = rgba(253, 2, 251, 1)
$font_color = rgba(134, 103, 183, 1)
$placeholder_color = rgba(134, 103, 183, 0.7)
$check_color = rgba(0, 211, 255, 1)
