# Background and foreground colors
background = #000002
foreground = #8667b7

# Standard colors
palette = 0=#000002
palette = 1=#f90020
palette = 2=#3dff05
palette = 3=#eaff0d
palette = 4=#ff78ff
palette = 5=#fd02fb
palette = 6=#00d3ff
palette = 7=#8667b7

# Bright colors
palette = 8=#525978
palette = 9=#ff4d63
palette = 10=#1e8f00
palette = 11=#879400
palette = 12=#f99ef9
palette = 13=#940593
palette = 14=#008799
palette = 15=#fcfcfc
