background            #000002
foreground            #8667b7

# black
color0  #000002
color8  #525978

# red
color1  #f90020
color9  #ff4d63

# green
color2  #3dff05
color10 #1e8f00

# yellow
color3  #eaff0d
color11 #879400

# blue
color4  #ff78ff
color12 #f99ef9

# magenta
color5  #fd02fb
color13 #940593

#cyan
color6  #00d3ff
color14 #008799

#white
color7  #8667b7
color15 #fcfcfc


