[general]
bars = 8
framerate = 60
autosens = 1

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1600
bar_delimiter = 32

[input]
method = pulse

[smoothing]
noise_reduction = 25
